services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_BASE_URL: http://46.101.32.120:8083/api
        NODE_ENV: development  # Pass to build stage
    image: baiks384/ridesharing-frontend
    container_name: ridesharing-frontend
    environment:
      NODE_ENV: development
    ports:
      - "8076:8076"
    restart: unless-stopped